language: node_js
node_js:
  - "0.10"
install:
  - npm install phantomjs -g
  - npm install -g mocha-phantomjs
  - npm install -g grunt
  - npm install
before_script:
  - phantomjs --version
  - mocha-phantomjs --version
  - grunt &
  - sleep 5 # give grunt background task some time to execute.
script:
  - mocha-phantomjs test/mocha-tests-server.html